### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dirien** [pulumi/esc-sdk#55]
### What happened?

When trying to read the default environment after pressing "new environment", I get a

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100b3f5d8]

goroutine 1 [running]:
github.com/pulumi/esc-sdk/sdk/go.(*EscClient).ReadOpenEnvironment(0x30?, {0x100c75c20?, 0x1400019d170?}, {0x100b4c206?, 0x140001f3e78?}, {0x100b4cabf?, 0x140001f3e78?}, {0x100b4c20b?, 0x10?}, {0x140001906c0?, ...})
        /Users/dirien/go/pkg/mod/github.com/pulumi/esc-sdk/sdk@v0.10.0/go/api_esc_extensions.go:104 +0xe8
github.com/pulumi/esc-sdk/sdk/go.(*EscClient).OpenAndReadEnvironment(0x14000027f18, {0x100c75c20, 0x1400019d170}, {0x100b4c206, 0x5}, {0x100b4cabf, 0x7}, {0x100b4c20b, 0x5})
        /Users/dirien/go/pkg/mod/github.com/pulumi/esc-sdk/sdk@v0.10.0/go/api_esc_extensions.go:127 +0x90
main.main()
        /private/tmp/esc-test/main.go:22 +0x294
exit status 2
```

### Example

This is my example client code:

```go
package main

import (
	"fmt"
	esc "github.com/pulumi/esc-sdk/sdk/go"
	"log"
	"os"
)

func main() {
	accessToken := os.Getenv("PULUMI_ACCESS_TOKEN")
	//projectName := "dirien"
	//orgName := "ediri"
	//envName := "joke-app"
	orgName := "ediri"
	projectName := "default"
	envName := "test2"
	configuration := esc.NewConfiguration()
	escClient := esc.NewClient(configuration)
	authCtx := esc.NewAuthContext(accessToken)

	_, values, err := escClient.OpenAndReadEnvironment(authCtx, orgName, projectName, envName)
	if err != nil {
		log.Fatalf("Failed to open and read environment: %v", err)
	}
	fmt.Println(values)
}
```

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by IaroslavTitov** [comment]
Fixed and released in https://github.com/pulumi/esc-sdk/pull/56
